book/urls.py
from django.urls import path
from . import views

app_name = 'book'

urlpatterns = [
    path('books/', views.book_list, name='book_list'),
    path('books/add', views.book_add, name='book_add'),
    path('books/edit/<str:book_slug>', views.book_edit, name='book_edit'),
    path('books/delete/<int:pk>', views.book_delete, name='book_delete'),
    path('books/<str:slug>', views.book_detail, name='book_detail'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
# to implement static and media files
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('book.urls', namespace='book')),
]

# static files.
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# media files.
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book/models.py
from django.contrib.auth.models import User
from django.db import models

def upload_img(instance, filename):
    extension = filename.split(".")[-1]
    renamed = f"{instance.name}.{extension}"
    return F"books/img/{renamed}"

def upload_files(instance, filename):
    extension = filename.split(".")[-1]
    renamed = f"{instance.name}.{extension}"
    return F"books/file/{renamed}"

# Category.
class Category(models.Model):
    title = models.CharField(max_length=100)
    
    def __str__(self):
        return self.title

# Book.
class Book(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True, null=True)
    img = models.ImageField(blank=True, null=True, upload_to=upload_img)
    file = models.FileField(blank=True, null=True, upload_to=upload_files)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='books')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='books')
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rate = models.DecimalField(max_digits=4, decimal_places=2)
    
    def __str__(self):
        return self.name

book/forms.py
from django import forms
from .models import Book

class AddNewBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'author', 'img', 'file', 'category', 'price', 'rate']

book/views.py
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import redirect, render
from django.utils.text import slugify

from .models import Book
from .forms import AddNewBookForm

# CRUD operations.
# Retrieve / get data.
# get book list.
def book_list(request):
    books = Book.objects.all()
    search_query = request.GET.get('q')
    if search_query:
        books = books.filter(
            Q(name__icontains=search_query) |
            Q(author__username__icontains=search_query)
        )

    context = {"books": books, 'name': 'sdfasfasdf'}
    print(books, search_query)
    return render(request, 'book/book_list.html', context=context)

# get specific book (by pk/slug...)
def book_detail(request, slug):
    book = Book.objects.get(slug=slug)
    return render(request, 'book/book_detail.html', context={'book': book})

# add new book
def book_add(request):
    form = AddNewBookForm()
    if request.method == "POST":
        form = AddNewBookForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.slug = slugify(instance.name)
            instance.save()
            messages.success(request, 'Book added successfully')
            
        return redirect('book:book_list')
    return render(request, 'book/add_book.html', context={'form': form})

# book edit.
def book_edit(request, book_slug):
    book = Book.objects.get(slug=book_slug)
    form = AddNewBookForm(instance=book)
    if request.method == 'POST':
        form = AddNewBookForm(request.POST, instance=book)
        if form.is_valid():
            form.save()
            messages.success(request, 'Book edited successfully')
            return redirect('book:book_detail', slug=book_slug)
    return render(request, 'book/add_book.html', {'form': form})

def book_delete(request, pk):
    book = Book.objects.get(pk=pk)
    book.delete()
    messages.success(request, 'Book deleted successfully!')
    return redirect('book:book_list')

book/templates/book/add_book.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block title %}
{{ block.super }} Add new
{% endblock %}

{% block content %}

  {% if form.instance.id %}
    <h1 class="display-1">Edit {{ form.instance.name }} </h1>
    <hr/>
  {% else %}
    <h1 class="display-1">Add new book!</h1>
    <hr/>
  {% endif %}
    <div class="col-sm-6 mx-auto">
    <form enctype="multipart/form-data" method="post" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <button type="submit" class="btn btn-dark mt-3">
          Submit
        </button>
      {% endbuttons %}
    </form>
    </div>


{% endblock %}

book/templates/book/book_detail.html
{% extends 'base.html' %}

{% block title %}
{{ block.super }} {{ book }}
{% endblock %}

{% block content %}
    <div class="row mt-5">
      <div class="col-sm-6 mx-auto">
        <div class="card">
          <img src="{{ book.img.url }}" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">{{ book.name }}</h5>
            <p class="card-text">author: {{ book.author }}</p>
            <p class="card-text">price: {{ book.price }}</p>
            <p class="card-text">category: {{ book.category }}</p>
            <p class="card-text">rate: {{ book.rate }}</p>
            <a href="{{ book.file.url}}" download class="btn btn-success">Download</a>
            <a href="{% url 'book:book_edit' book.slug %}"  class="btn btn-success">Edit</a>
          </div>
        </div>
      </div>
    </div>


{% endblock %}

book/templates/book/book_list.html
{% extends 'base.html' %}

{% block title %}
{{ block.super }} Book list
{% endblock %}

{% block content %}
  {% if request.GET.q %}
    <h1 class="display-1">searching for: <b class="text-success">{{ request.GET.q }}</b></h1>
  {% else %}
    <h1 class="display-1">All Books!</h1>
  {% endif %}
    <div class="row">
      {% for book in books %}
      <div class="col-sm-4">
        <div class="card">
          {% if book.img %}
            <img src="{{ book.img.url }}" class="card-img-top" alt="...">
          {% endif %}
          <div class="card-body">
            <h5 class="card-title">{{ book.name }}</h5>
            <p class="card-text">author: {{ book.author }}</p>
            {% if book.file %}
              <a href="{{ book.file.url}}" download class="btn btn-success">Download</a>
            {% endif %}
            <a href="{% url 'book:book_detail' book.slug %}"  class="btn btn-warning">read more.</a>
            <a href="{% url 'book:book_delete' book.pk %}"  class="btn btn-danger">Delete</a>
          </div>
        </div>
      </div>
  {% endfor %}
    </div>


{% endblock %}

book/templates/book/home.html
{% extends 'base.html' %}

{% block title %}
{{ block.super }} Home page
{% endblock %}

{% block content %}
  <h1 class="display-1">Welcome to Book App!</h1>

{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
{#    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">#}
    <link rel="stylesheet" href="{% static 'styles/bootstrap.min.css' %}">

    <title>
      {% block title %}
        Book App|
      {% endblock %}
    </title>
  </head>
  <body>
  <nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand">Book App!</a>
      <form class="d-flex">
        <input value="{{ request.GET.q }}" class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
    </nav>
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message|safe }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
    {% endif %}

    <div class="container">
      {% block content %}

      {% endblock %}
    </div>

{#    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>#}
  <scripr src="{% static 'jcccs/bootstrap.min.css' %}"></scripr>
  </body>
</html>